steps:
  - command: "pylint simulated_robot.py"
    label: ":python::lint:"
    soft_fail: true

  - command: "pylint controller.py"
    label: ":python::lint:"
    soft_fail: true

  - wait: ~

  - command: "docker buildx build -t simulated_robot:$$BUILDKITE_COMMIT -f Dockerfile.simulated_robot ."
    label: ":docker: Build simulated_robot image"
    branches: "!master"

  - command: "docker buildx build -t controller:$$BUILDKITE_COMMIT -f Dockerfile.controller ."
    label: ":docker: Build controller image"
    branches: "!master"
    
  - command:
    - "docker buildx build -t simulated_robot:$$BUILDKITE_COMMIT -f Dockerfile.simulated_robot ."
    - "aws ecr get-login-password --region $$AWS_REGION | docker login --username AWS --password-stdin $$AWS_ACCOUNT_NUMBER.dkr.ecr.$$AWS_REGION.amazonaws.com"
    - "docker tag simulated_robot:$$BUILDKITE_COMMIT $$AWS_ACCOUNT_NUMBER.dkr.ecr.$$AWS_REGION.amazonaws.com/simulated_robot:latest"
    - "docker push $$AWS_ACCOUNT_NUMBER.dkr.ecr.$$AWS_REGION.amazonaws.com/simulated_robot:latest"
    label: ":docker::aws: Build & upload simulated_robot image"
    branches: "master"
    
  - command:
    - "docker buildx build -t controller:$$BUILDKITE_COMMIT -f Dockerfile.controller ."
    - "aws ecr get-login-password --region $$AWS_REGION | docker login --username AWS --password-stdin $$AWS_ACCOUNT_NUMBER.dkr.ecr.$$AWS_REGION.amazonaws.com"
    - "docker tag controller:$$BUILDKITE_COMMIT $$AWS_ACCOUNT_NUMBER.dkr.ecr.$$AWS_REGION.amazonaws.com/controller:latest"
    - "docker push $$AWS_ACCOUNT_NUMBER.dkr.ecr.$$AWS_REGION.amazonaws.com/controller:latest"
    label: ":docker::aws: Build & upload controller image"
    branches: "master"